version: '3.3'

services:

  bmie:
    build: .
    restart: "no"
    ports:
      - 7000:5000
    environment:
      ENV: 'DEV'
      SQLALCHEMY_DATABASE_URI: 'mssql+pyodbc://sa:example123!@host.docker.internal:1433/bsmdb?driver=ODBC+Driver+17+for+SQL+Server'
      SECRET_KEY: 'You_Secret_Key'
